In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('titanic.csv')

In [2]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
columns_target=['Survived']

In [4]:
columns_train=['Age','Pclass','Sex','Fare']

In [5]:
X=data[columns_train]
Y=data[columns_target]

In [6]:
X['Sex'].isnull().sum()

0

In [7]:
X['Pclass'].isnull().sum()

0

In [8]:
X['Fare'].isnull().sum()

0

In [9]:
X['Age'].isnull().sum()

177

In [10]:
X['Age']=X['Age'].fillna(X['Age'].median())

C:\Users\wulfi\AppData\Local\Temp\ipykernel_1228\667372840.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Age']=X['Age'].fillna(X['Age'].median())


In [11]:
X['Age'].isnull().sum()

0

In [12]:
X['Age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [13]:
d={'male':0,'female':1}

In [14]:
X['Sex']=X['Sex'].apply(lambda x:d[x])

C:\Users\wulfi\AppData\Local\Temp\ipykernel_1228\1927810309.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Sex']=X['Sex'].apply(lambda x:d[x])


In [15]:
X['Sex'].head()

0    0
1    1
2    1
3    1
4    0
Name: Sex, dtype: int64

In [16]:
X.head()

Age  Pclass  Sex     Fare
0  22.0       3    0   7.2500
1  38.0       1    1  71.2833
2  26.0       3    1   7.9250
3  35.0       1    1  53.1000
4  35.0       3    0   8.0500

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33,random_state=42)

In [19]:
from sklearn import svm

In [20]:
clf=svm.LinearSVC()
clf.fit(X_train,Y_train)

c:\users\wulfi\pycharmprojects\parsing\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\wulfi\pycharmprojects\parsing\venv\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [21]:
clf.predict(X_test[0:10])

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [22]:
clf.score(X_test,Y_test)

0.6406779661016949

In [23]:
from sklearn.linear_model import LogisticRegression

In [25]:
LR = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr').fit(X_train, Y_train) 

c:\users\wulfi\pycharmprojects\parsing\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
LR.predict(X_test[0:10])

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [27]:
LR.score(X_test,Y_test)

0.8067796610169492

In [29]:
import sklearn as sk 
from sklearn.ensemble import RandomForestClassifier

In [31]:
RF = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0).fit(X_train, Y_train)

C:\Users\wulfi\AppData\Local\Temp\ipykernel_1228\3542937348.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RF = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0).fit(X_train, Y_train)


In [32]:
RF.predict(X_test[0:10])

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1], dtype=int64)

In [33]:
RF.score(X_test,Y_test)

0.7898305084745763

In [34]:
from sklearn.neural_network import MLPClassifier

In [35]:
NN = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1).fit(X_train, Y_train)

c:\users\wulfi\pycharmprojects\parsing\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [36]:
NN.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [37]:
NN.score(X_test,Y_test)

0.5932203389830508